import { PRODUTOS, CATEGORIAS, moeda } from '../src/catalogo.js';
import { BANNER_CUIDADOS, BANNER_CABELOS, BANNER_PROTECAO } from '../src/banners-v20.js';

const LOGO = '../assets/logo-rocha-oficial.webp';
const app = document.querySelector('#app');
const state = { cart: JSON.parse(localStorage.getItem('rocha-v2-cart') || '{}'), banner: 0, query: '', category: 'todos' };
const icons = {
 search:'<svg viewBox="0 0 24 24"><circle cx="11" cy="11" r="6"/><path d="m16 16 4 4"/></svg>',
 truck:'<svg viewBox="0 0 24 24"><path d="M3 6h11v10H3zM14 10h4l3 3v3h-7z"/><circle cx="7" cy="18" r="2"/><circle cx="18" cy="18" r="2"/></svg>',
 home:'<svg viewBox="0 0 24 24"><path d="m3 11 9-8 9 8M5 10v11h14V10M9 21v-7h6v7"/></svg>',
 file:'<svg viewBox="0 0 24 24"><path d="M6 3h9l3 3v15H6zM14 3v4h4M9 11h6M9 15h4"/></svg>',
 plus:'<svg viewBox="0 0 24 24"><path d="M12 5v14M5 12h14"/></svg>',
 phone:'<svg viewBox="0 0 24 24"><path d="M7 4 4 7c1 7 6 12 13 13l3-3-4-3-2 2c-3-1-5-3-6-6l2-2z"/></svg>',
 sun:'<svg viewBox="0 0 24 24"><circle cx="12" cy="12" r="4"/><path d="M12 2v2M12 20v2M2 12h2M20 12h2M5 5l1.5 1.5M17.5 17.5 19 19M5 19l1.5-1.5M17.5 6.5 19 5"/></svg>'
};
const count = () => Object.values(state.cart).reduce((a,b)=>a+b,0);
const save = () => { localStorage.setItem('rocha-v2-cart',JSON.stringify(state.cart)); updateCount(); };

function render(){
 app.innerHTML=`
 <div class="topline"><div class="shell"><span><strong>Drogaria Rocha</strong> — cuidado perto de você</span><div class="topline-links"><span>Atendimento</span><span>Envie sua receita</span><span>Retirada ou entrega</span></div></div></div>
 <header class="header"><div class="shell header-main">
  <a class="brand" href="#inicio"><img src="${LOGO}" alt="Drogaria Rocha"><span class="brand-copy"><small>DROGARIA</small><strong>ROCHA</strong></span></a>
  <label class="search">${icons.search}<input id="search" type="search" placeholder="O que você está procurando?" aria-label="Buscar produtos"></label>
  <button class="delivery" data-help><span>Entregar ou retirar</span><strong>Consulte nossa equipe</strong></button>
  <button class="cart-btn" data-cart><span>Meu carrinho</span><b data-count>0</b></button>
 </div><nav class="departments"><div class="shell"><button data-cat="todos">Todos os produtos</button><button data-cat="limpeza">Dermocosméticos</button><button data-cat="protecao">Proteção solar</button><button data-cat="shampoo">Cabelos</button><button data-cat="coloracao">Coloração</button><button data-recipe>Enviar receita</button><button class="offers" data-scroll="ofertas">Ofertas</button></div></nav></header>
 <main id="inicio">
  <section class="hero"><div class="shell"><div class="hero-window"><div class="hero-track">
   ${hero(BANNER_CUIDADOS,'Cuidados diários','Higiene e beleza para sua rotina','Uma seleção prática para cuidar de você e da sua família.','Ver ofertas','')}
   ${hero(BANNER_CABELOS,'Cuidado capilar','Tudo para seus cabelos','Shampoos, tratamentos e colorações em um só lugar.','Explorar produtos','dark')}
   ${hero(BANNER_PROTECAO,'Proteção e bem-estar','Cuidados essenciais sempre perto','Proteção solar e bem-estar para completar sua rotina.','Ver proteção','')}
  </div><div class="hero-dots">${[0,1,2].map(i=>`<button data-dot="${i}" aria-label="Banner ${i+1}"></button>`).join('')}</div></div></div></section>
  <section class="shell advantages">${adv('truck','Entrega combinada','Consulte a disponibilidade')}${adv('home','Retire na drogaria','Reserve antes de sair')}${adv('file','Envie sua receita','Solicite uma cotação')}${adv('plus','Orientação farmacêutica','Atendimento responsável')}${adv('phone','Fale com a equipe','Atendimento pelo WhatsApp')}</section>
  <section class="shell section" id="ofertas"><div class="section-head"><h2>Ofertas do dia</h2><button data-cat="todos">Ver todos os produtos</button></div>${shelf('offers',PRODUTOS.slice(0,12))}</section>
  <section class="shell campaigns"><article class="campaign"><div><span class="tag">CUIDADO DIÁRIO</span><h2>Envie sua receita pelo celular</h2><p>Fotografe a receita e solicite uma cotação diretamente com nossa equipe.</p><button class="cta" data-recipe>Enviar receita</button></div></article><article class="campaign dark"><div><span class="tag">ATENDIMENTO</span><h2>Não encontrou?</h2><p>Fale com a Drogaria Rocha.</p><button class="cta" data-help>Chamar no WhatsApp</button></div></article></section>
  <section class="shell section"><div class="section-head"><h2>Cuidados para cabelos</h2><button data-cat="shampoo">Ver categoria</button></div>${shelf('hair',PRODUTOS.filter(p=>['shampoo','tratamento-capilar'].includes(p.categoria)).slice(0,12))}</section>
  <section class="categories"><div class="shell"><div class="section-head"><h2>Compre por categoria</h2></div><div class="category-grid">${categoryButtons()}</div></div></section>
  <section class="shell help"><div><h2>Precisa de ajuda para encontrar um produto?</h2><p>Nossa equipe confere disponibilidade e orienta você na finalização.</p></div><button class="cta" data-help>Falar com a drogaria</button></section>
 </main>
 <footer><div class="shell footer-grid"><div><div class="footer-brand"><img src="${LOGO}" alt=""><strong>Drogaria Rocha</strong></div><p>Cuidado, confiança e atendimento próximo.</p></div><div><h3>Atendimento</h3><p>Consulte horários, retirada e entrega diretamente com nossa equipe.</p></div><div><h3>Uso responsável</h3><p>Medicamentos podem exigir receita e avaliação farmacêutica. Não se automedique.</p></div></div></footer>
 <div class="overlay" id="overlay"><div id="overlay-content"></div></div>
 <nav class="mobile-nav"><button data-scroll="inicio"><strong>⌂</strong>Início</button><button data-scroll="ofertas"><strong>⌕</strong>Produtos</button><button data-recipe><strong>▤</strong>Receita</button><button data-cart><strong>▣</strong>Carrinho</button></nav>`;
 bind(); updateCount(); setBanner(0); startBanner();
}
function hero(img,tag,title,text,button,cls){return `<article class="hero-slide ${cls}"><img src="${img}" alt=""><div class="hero-copy"><span class="tag">${tag}</span><h1>${title}</h1><p>${text}</p><button class="cta" data-scroll="ofertas">${button}</button></div></article>`}
function adv(icon,title,text){return `<article class="advantage"><span class="adv-icon">${icons[icon]}</span><div><strong>${title}</strong><small>${text}</small></div></article>`}
function shelf(id,products){return `<div class="shelf-wrap"><button class="shelf-arrow prev" data-shelf="${id}" data-dir="-1">‹</button><div class="shelf" id="${id}">${products.map(productCard).join('')}</div><button class="shelf-arrow next" data-shelf="${id}" data-dir="1">›</button></div>`}
function productCard(p){const q=state.cart[p.id]||0;return `<article class="product" data-product="${p.id}"><div class="product-image"><img src="${p.imagem}" alt="${p.nome}" loading="lazy">${p.selo?`<span class="badge">${p.selo}</span>`:''}</div><div class="product-body"><span class="product-category">${CATEGORIAS.find(c=>c.id===p.categoria)?.nome||''}</span><h3>${p.nome}</h3><span class="stock">● Disponível para consulta</span><div class="product-bottom"><div class="price"><small>A partir de</small><strong>${moeda(p.preco)}</strong></div>${q?`<div class="qty"><button data-minus="${p.id}">−</button><b>${q}</b><button data-plus="${p.id}">+</button></div>`:`<button class="add" data-plus="${p.id}">Adicionar</button>`}</div></div></article>`}
function categoryButtons(){return [{id:'protecao',n:'Proteção solar',s:'Cuidados diários'},{id:'hidratacao',n:'Hidratação',s:'Rosto e corpo'},{id:'limpeza',n:'Limpeza facial',s:'Pele bem cuidada'},{id:'coloracao',n:'Coloração',s:'Renove o visual'},{id:'shampoo',n:'Shampoos',s:'Todos os tipos'},{id:'tratamento-capilar',n:'Tratamentos',s:'Nutrição capilar'}].map(c=>`<button class="category" data-cat="${c.id}">${icons.sun}<strong>${c.n}</strong><small>${c.s}</small></button>`).join('')}
function setBanner(i){state.banner=(i+3)%3;document.querySelector('.hero-track').style.transform=`translateX(-${state.banner*100}%)`;document.querySelectorAll('[data-dot]').forEach((d,n)=>d.classList.toggle('active',n===state.banner))}
let timer;function startBanner(){clearInterval(timer);timer=setInterval(()=>setBanner(state.banner+1),4500)}
function change(id,delta){state.cart[id]=Math.max(0,(state.cart[id]||0)+delta);if(!state.cart[id])delete state.cart[id];save();renderShelves()}
function renderShelves(){document.querySelector('#offers').parentElement.outerHTML=shelf('offers',PRODUTOS.slice(0,12));const hair=document.querySelector('#hair');if(hair)hair.parentElement.outerHTML=shelf('hair',PRODUTOS.filter(p=>['shampoo','tratamento-capilar'].includes(p.categoria)).slice(0,12));bindProducts()}
function updateCount(){document.querySelectorAll('[data-count]').forEach(el=>el.textContent=count())}
function openOverlay(html){document.querySelector('#overlay-content').innerHTML=html;document.querySelector('#overlay').classList.add('open');document.body.style.overflow='hidden';document.querySelectorAll('[data-close]').forEach(b=>b.onclick=closeOverlay)}
function closeOverlay(){document.querySelector('#overlay').classList.remove('open');document.body.style.overflow=''}
function openProduct(id){const p=PRODUTOS.find(x=>x.id===id);openOverlay(`<section class="product-dialog"><button class="close" data-close>×</button><div class="dialog-image"><img src="${p.imagem}" alt="${p.nome}"></div><div class="dialog-info"><span class="tag">${CATEGORIAS.find(c=>c.id===p.categoria)?.nome}</span><h2>${p.nome}</h2><p>${p.descricao}</p><div class="dialog-price"><small>Preço demonstrativo</small><strong>${moeda(p.preco)}</strong><p>Valor e disponibilidade confirmados antes da finalização.</p></div><button class="add" data-dialog-add="${p.id}">Adicionar ao carrinho</button></div></section>`);document.querySelector('[data-dialog-add]').onclick=()=>{change(p.id,1);closeOverlay()}}
function openCart(){const items=Object.entries(state.cart).map(([id,q])=>[PRODUTOS.find(p=>p.id==id),q]);openOverlay(`<aside class="drawer"><div class="drawer-head"><h2>Meu carrinho</h2><button class="close" data-close>×</button></div>${items.length?items.map(([p,q])=>`<div class="cart-item"><img src="${p.imagem}" alt=""><div><h4>${p.nome}</h4><strong>${moeda(p.preco)}</strong></div><div class="qty"><button data-cart-minus="${p.id}">−</button><b>${q}</b><button data-cart-plus="${p.id}">+</button></div></div>`).join(''):`<div class="empty"><h3>Seu carrinho está vazio</h3><p>Escolha produtos nas prateleiras.</p></div>`}</aside>`);document.querySelectorAll('[data-cart-plus]').forEach(b=>b.onclick=()=>{change(+b.dataset.cartPlus,1);openCart()});document.querySelectorAll('[data-cart-minus]').forEach(b=>b.onclick=()=>{change(+b.dataset.cartMinus,-1);openCart()})}
function bindProducts(){document.querySelectorAll('[data-plus]').forEach(b=>b.onclick=e=>{e.stopPropagation();change(+b.dataset.plus,1)});document.querySelectorAll('[data-minus]').forEach(b=>b.onclick=e=>{e.stopPropagation();change(+b.dataset.minus,-1)});document.querySelectorAll('[data-product]').forEach(c=>c.onclick=()=>openProduct(+c.dataset.product));document.querySelectorAll('[data-shelf]').forEach(b=>b.onclick=()=>document.querySelector('#'+b.dataset.shelf).scrollBy({left:+b.dataset.dir*720,behavior:'smooth'}))}
function bind(){bindProducts();document.querySelectorAll('[data-dot]').forEach(b=>b.onclick=()=>{setBanner(+b.dataset.dot);startBanner()});document.querySelectorAll('[data-cart]').forEach(b=>b.onclick=openCart);document.querySelectorAll('[data-help]').forEach(b=>b.onclick=()=>window.open('https://wa.me/?text='+encodeURIComponent('Olá, Drogaria Rocha! Preciso de ajuda para encontrar um produto.'),'_blank'));document.querySelectorAll('[data-recipe]').forEach(b=>b.onclick=()=>openOverlay(`<aside class="drawer"><div class="drawer-head"><h2>Enviar receita</h2><button class="close" data-close>×</button></div><p>Fotografe a receita com todos os dados visíveis.</p><label class="search"><input type="file" accept="image/*,.pdf"></label><button class="cta" data-help>Continuar pelo WhatsApp</button></aside>`));document.querySelectorAll('[data-scroll]').forEach(b=>b.onclick=()=>document.querySelector('#'+b.dataset.scroll)?.scrollIntoView({behavior:'smooth'}));document.querySelectorAll('[data-cat]').forEach(b=>b.onclick=()=>{state.category=b.dataset.cat;const list=state.category==='todos'?PRODUTOS:PRODUTOS.filter(p=>p.categoria===state.category);document.querySelector('#offers').parentElement.outerHTML=shelf('offers',list);bindProducts();document.querySelector('#ofertas').scrollIntoView({behavior:'smooth'})});document.querySelector('#search').oninput=e=>{const q=e.target.value.toLowerCase();const list=PRODUTOS.filter(p=>(p.nome+' '+p.descricao).toLowerCase().includes(q));document.querySelector('#offers').parentElement.outerHTML=shelf('offers',list);bindProducts()};document.querySelector('#overlay').onclick=e=>{if(e.target.id==='overlay')closeOverlay()}}
render();
