-- Drogaria Rocha - MVP Plataforma
-- 2026-08-18
-- Execute no SQL Editor do Supabase do projeto usado pelo aplicativo.

begin;

create table if not exists public.stores (
  id smallint primary key,
  name text not null,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

insert into public.stores (id, name)
values
  (1, 'Drogaria Rocha - Loja 1'),
  (2, 'Drogaria Rocha - Loja 2')
on conflict (id) do update set name = excluded.name;

create table if not exists public.profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  name text,
  phone text,
  cpf text,
  birth_date date,
  marketing_consent boolean not null default false,
  notification_orders boolean not null default true,
  notification_promotions boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.orders (
  id uuid primary key default gen_random_uuid(),
  code text not null unique,
  user_id uuid references auth.users(id) on delete set null,
  customer_name text not null check (char_length(customer_name) between 2 and 120),
  phone text not null check (char_length(phone) between 8 and 30),
  email text,
  store_id smallint not null references public.stores(id),
  fulfillment text not null check (fulfillment in ('delivery','pickup')),
  address text,
  payment_method text not null check (payment_method in ('pix','cash','credit','debit','delivery')),
  change_for numeric(12,2),
  notes text,
  subtotal numeric(12,2) not null check (subtotal >= 0),
  delivery_fee numeric(12,2) not null default 0 check (delivery_fee >= 0),
  total numeric(12,2) not null check (total >= 0),
  status text not null default 'received'
    check (status in ('received','confirmed','separating','ready','out_for_delivery','delivered','cancelled')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.order_items (
  id bigint generated by default as identity primary key,
  order_id uuid not null references public.orders(id) on delete cascade,
  product_id bigint,
  product_name text not null,
  quantity integer not null check (quantity > 0 and quantity <= 100),
  unit_price numeric(12,2) not null check (unit_price >= 0),
  total numeric(12,2) not null check (total >= 0)
);

create table if not exists public.order_status_history (
  id bigint generated by default as identity primary key,
  order_id uuid not null references public.orders(id) on delete cascade,
  old_status text,
  new_status text not null,
  changed_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);

create table if not exists public.inventory (
  store_id smallint not null references public.stores(id) on delete cascade,
  product_id bigint not null,
  quantity integer not null default 0 check (quantity >= 0),
  minimum_stock integer not null default 0 check (minimum_stock >= 0),
  updated_at timestamptz not null default now(),
  primary key (store_id, product_id)
);

create index if not exists orders_user_created_idx on public.orders(user_id, created_at desc);
create index if not exists orders_status_created_idx on public.orders(status, created_at desc);
create index if not exists orders_store_created_idx on public.orders(store_id, created_at desc);
create index if not exists order_items_order_idx on public.order_items(order_id);
create index if not exists order_history_order_idx on public.order_status_history(order_id, created_at);

create or replace function public.touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_profiles_updated_at on public.profiles;
create trigger trg_profiles_updated_at
before update on public.profiles
for each row execute function public.touch_updated_at();

drop trigger if exists trg_orders_updated_at on public.orders;
create trigger trg_orders_updated_at
before update on public.orders
for each row execute function public.touch_updated_at();

create or replace function public.log_order_status_change()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if tg_op = 'INSERT' then
    insert into public.order_status_history(order_id, old_status, new_status, changed_by)
    values (new.id, null, new.status, auth.uid());
  elsif new.status is distinct from old.status then
    insert into public.order_status_history(order_id, old_status, new_status, changed_by)
    values (new.id, old.status, new.status, auth.uid());
  end if;
  return new;
end;
$$;

drop trigger if exists trg_order_status_history on public.orders;
create trigger trg_order_status_history
after insert or update of status on public.orders
for each row execute function public.log_order_status_change();

alter table public.stores enable row level security;
alter table public.profiles enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;
alter table public.order_status_history enable row level security;
alter table public.inventory enable row level security;

drop policy if exists stores_public_read on public.stores;
create policy stores_public_read
on public.stores for select
using (active = true or public.is_admin());

drop policy if exists profiles_own_read on public.profiles;
create policy profiles_own_read
on public.profiles for select
using (auth.uid() = user_id or public.is_admin());

drop policy if exists profiles_own_insert on public.profiles;
create policy profiles_own_insert
on public.profiles for insert
with check (auth.uid() = user_id);

drop policy if exists profiles_own_update on public.profiles;
create policy profiles_own_update
on public.profiles for update
using (auth.uid() = user_id or public.is_admin())
with check (auth.uid() = user_id or public.is_admin());

drop policy if exists orders_read on public.orders;
create policy orders_read
on public.orders for select
using ((auth.uid() is not null and auth.uid() = user_id) or public.is_admin());

-- MVP: permite criar pedido com ou sem login para não aumentar atrito no checkout.
-- Antes de escalar campanhas, recomenda-se mover a criação para uma Edge Function
-- com rate limit/captcha.
drop policy if exists orders_insert on public.orders;
create policy orders_insert
on public.orders for insert
with check (user_id is null or auth.uid() = user_id);

drop policy if exists orders_admin_update on public.orders;
create policy orders_admin_update
on public.orders for update
using (public.is_admin())
with check (public.is_admin());

drop policy if exists order_items_read on public.order_items;
create policy order_items_read
on public.order_items for select
using (
  exists (
    select 1 from public.orders o
    where o.id = order_items.order_id
      and ((auth.uid() is not null and o.user_id = auth.uid()) or public.is_admin())
  )
);

drop policy if exists order_items_insert on public.order_items;
create policy order_items_insert
on public.order_items for insert
with check (
  exists (
    select 1 from public.orders o
    where o.id = order_items.order_id
      and (o.user_id is null or o.user_id = auth.uid() or public.is_admin())
  )
);

drop policy if exists order_history_read on public.order_status_history;
create policy order_history_read
on public.order_status_history for select
using (
  exists (
    select 1 from public.orders o
    where o.id = order_status_history.order_id
      and ((auth.uid() is not null and o.user_id = auth.uid()) or public.is_admin())
  )
);

drop policy if exists inventory_public_read on public.inventory;
create policy inventory_public_read
on public.inventory for select
using (true);

drop policy if exists inventory_admin_all on public.inventory;
create policy inventory_admin_all
on public.inventory for all
using (public.is_admin())
with check (public.is_admin());

commit;
